[project]
name = 'decentralized-content-monetization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.content-tokenization-vault]
path = 'contracts/content-tokenization-vault.clar'
clarity_version = 2
epoch = 2.5

[contracts.creator-revenue-distributor]
path = 'contracts/creator-revenue-distributor.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
